// Writes database/ops/2026-09-30-prod-reset.sql from tables.mjs — the one
// classification. Re-run after editing tables.mjs; the pinning test
// (src/lib/__tests__/prod-reset-tables.test.ts) checks the output.
import { writeFileSync } from 'node:fs';
import { KEEP, PARTIAL, goTables } from './tables.mjs';

const go = goTables();
const list = go.map(t => `  public.${t}`).join(',\n');
const keepChecks = KEEP.map(t => `  INSERT INTO _reset_result SELECT 'KEEP ${t}', count(*) FROM public.${t};`).join('\n');
const partial = Object.entries(PARTIAL).map(([t, where]) => `DELETE FROM public.${t} WHERE ${where};`).join('\n');

const sql = `-- ============================================================================
-- Production reset — Sep 30 2026: a clean slate on edgeathlete.ca
-- ============================================================================
-- Tom (Sep 29 2026): the site went live ahead of schedule with two months of
-- test data; "remove all users so the website is clean and brand new with no
-- user data. I want the functionality to remain the same."
--
-- ONE-OFF. Not a migration: no DDL, not in the chain, not in the ledger.
-- Generated by scripts/prod-reset/generate-sql.mjs from
-- scripts/prod-reset/tables.mjs (the one classification; pinned by
-- src/lib/__tests__/prod-reset-tables.test.ts). Run ONCE in the prod SQL
-- editor (one transaction), AFTER scripts/prod-reset/export.mjs took the
-- snapshot and BEFORE scripts/prod-reset/wipe.mjs empties storage + auth.
--
-- KEEPS (reference data): ${KEEP.join(', ')};
-- and search_documents rows of entity_type = 'course' (the catalog's index).
-- WIPES: every other public table (${go.length} tables), RESTART IDENTITY
-- (tickets.number starts at 1000 again). No CASCADE on purpose: no kept
-- table references a wiped one (the test holds it), so a table missing from
-- the list makes Postgres REFUSE rather than truncate something extra.
-- Row triggers do not fire on TRUNCATE — the search index is cleared here
-- explicitly. Storage objects and auth.users are the wipe script's.
-- ============================================================================

-- ── 0. Pre-flight: this is production at the expected state ────────────────
DO $$
DECLARE head int; handles int; t text; n bigint;
BEGIN
  SELECT max(number) INTO head FROM public.schema_migrations;
  IF head <> 245 THEN RAISE EXCEPTION 'reset pre-flight: ledger head is %, expected 245', head; END IF;
  SELECT count(*) INTO handles FROM public.reserved_handles;
  IF handles < 100 THEN RAISE EXCEPTION 'reset pre-flight: reserved_handles has % rows — not the expected database', handles; END IF;
  FOREACH t IN ARRAY ARRAY['profiles', 'posts', 'golf_rounds', 'organizations', 'events', 'tickets', 'consent_records', 'venues'] LOOP
    EXECUTE format('SELECT count(*) FROM public.%I', t) INTO n;
    RAISE NOTICE 'before: % = %', t, n;
  END LOOP;
END $$;

-- ── 1. The wipe ─────────────────────────────────────────────────────────────
TRUNCATE TABLE
${list}
RESTART IDENTITY;

${partial}

-- ── 2. Result grid: every wiped table at 0, the kept ones as they were ───────
CREATE TEMP TABLE _reset_result (what text, rows_after bigint) ON COMMIT DROP;
DO $$
DECLARE t text; n bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY[${go.map(t => `'${t}'`).join(', ')}] LOOP
    EXECUTE format('SELECT count(*) FROM public.%I', t) INTO n;
    INSERT INTO _reset_result VALUES ('wiped ' || t, n);
  END LOOP;
END $$;
${keepChecks}
  INSERT INTO _reset_result SELECT 'KEEP search_documents (courses)', count(*) FROM public.search_documents;
  INSERT INTO _reset_result SELECT 'search_documents non-course (expect 0)', count(*) FROM public.search_documents WHERE ${PARTIAL.search_documents};

-- Expected: every 'wiped …' row = 0; 'search_documents non-course' = 0;
-- KEEP rows unchanged (golf_courses 28973, places 69641, place_aliases
-- 247077, golf_clubs 32, reserved_handles 102, schema_migrations 244 rows).
SELECT * FROM (
  SELECT what, rows_after,
         CASE WHEN what LIKE 'wiped %' OR what LIKE '%(expect 0)' THEN CASE WHEN rows_after = 0 THEN 'OK' ELSE 'NOT EMPTY' END ELSE 'kept' END AS status
    FROM _reset_result
) r
 ORDER BY (status = 'OK'), what; -- problems and the kept tables first
`;
writeFileSync('database/ops/2026-09-30-prod-reset.sql', sql);
console.log(`wrote database/ops/2026-09-30-prod-reset.sql — ${go.length} tables wiped, ${KEEP.length} kept`);
