/**
 * The in-app surface, derived — Site Builder phase 1 (Sep 9 2026).
 *
 * The design doc: the admin composes ONE layout (the web site); the app
 * page is generated by filtering to app-flagged widgets, ordering by each
 * widget's `appPriority`, sizing by `appSize`, compacting. Phase 1 derives
 * from the REGISTRY alone, not from a stored composition: an org without a
 * site row still has an in-app page, and the Photos bubble shows regardless
 * of the gallery module toggle (Org Pages R4). When a stored composition
 * drives this (phase 3+), orgs without one keep this registry order as the
 * default composition.
 *
 * The recorded priorities reproduce the glance grid's Sep 9 push order
 * exactly (pinned by app-layout.test.ts) — zero visual change.
 */

import { WIDGETS, WIDGET_KEYS, type AppBubbleKey, type BubbleSpan, type WidgetKey } from './catalog';

export interface AppSlot {
  key: WidgetKey;
  bubbleKey: AppBubbleKey;
  span: BubbleSpan;
  priority: number;
  ownsWindow: boolean;
}

/** Registry → the in-app glance order (ascending priority). */
export function deriveAppLayout(): AppSlot[] {
  const slots: AppSlot[] = [];
  for (const key of WIDGET_KEYS) {
    const app = WIDGETS[key].surfaces.app;
    if (!app) continue;
    slots.push({ key, bubbleKey: app.bubbleKey, span: app.size, priority: app.priority, ownsWindow: app.ownsWindow === true });
  }
  return slots.sort((a, b) => a.priority - b.priority);
}

/** The bubbles whose window the glance grid hosts (deep-link `?window=`
 *  validation) — every app slot except the ones that own their window. */
export type OrgWindowKey = Exclude<AppBubbleKey, 'posts'>;
export const APP_WINDOW_KEYS: readonly OrgWindowKey[] = deriveAppLayout()
  .filter(s => !s.ownsWindow)
  .map(s => s.bubbleKey as OrgWindowKey);

export function isOrgWindowKey(value: unknown): value is OrgWindowKey {
  return typeof value === 'string' && (APP_WINDOW_KEYS as readonly string[]).includes(value);
}
